//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOW_LOG
    {
        public int id { get; set; }
        public string s_class { get; set; }
        public string s_type { get; set; }
        public string s_sys { get; set; }
        public string s_no { get; set; }
        public Nullable<int> s_source { get; set; }
        public System.DateTime n_time { get; set; }
        public Nullable<System.DateTime> n_time_old { get; set; }
        public string s_status { get; set; }
        public string s_status_old { get; set; }
        public string s_msg { get; set; }
        public bool is_notify { get; set; }
        public bool is_transfer { get; set; }
    
        public virtual MonitorProperty MonitorProperty { get; set; }
    }
}
