//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_LOG
    {
        public int id { get; set; }
        public string sys_name { get; set; }
        public string sys_action { get; set; }
        public Nullable<System.DateTime> sys_stime { get; set; }
        public Nullable<System.DateTime> sys_etime { get; set; }
        public Nullable<int> sys_a_count { get; set; }
        public Nullable<int> sys_s_count { get; set; }
        public Nullable<int> sys_f_count { get; set; }
        public string sys_msg { get; set; }
        public Nullable<bool> sys_result { get; set; }
    }
}
