//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpNotifyList
    {
        public int id { get; set; }
        public Nullable<int> g_id { get; set; }
        public string u_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_account { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string update_account { get; set; }
        public string review_account { get; set; }
        public Nullable<System.DateTime> review_time { get; set; }
    
        public virtual TmpNotifyGroup TmpNotifyGroup { get; set; }
        public virtual TmpUsers TmpUsers { get; set; }
    }
}
