//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMD
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Monitor_Data
    {
        public string 監控項目編號 { get; set; }
        public Nullable<System.DateTime> 回報時間 { get; set; }
        public string 回報結果 { get; set; }
        public string 前次回報結果 { get; set; }
        public string 環境 { get; set; }
        public string 分類 { get; set; }
        public string 系統別 { get; set; }
        public string 監控項目主旨 { get; set; }
        public string 系統負責人 { get; set; }
        public string s_class { get; set; }
        public string s_type { get; set; }
        public string s_sys { get; set; }
        public string 回報資料 { get; set; }
        public string 是否由HostMonitor監控 { get; set; }
        public int 順序 { get; set; }
    }
}
